Milestone 2: Finished the Portfolio-works section
prg-04/Portfolio pull request #2
Opened 2022-10-28 07:17 UTC by prg-04

## In this Milestone, I have done the following step to set up a " Portfolio-Works section"

- [ ] Use grid layout and flexbox to set up the works and about me section

2022-10-28 10:19 UTC, Owusu-Desmond requested changes
Hi @prg-04 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._
- [ ] Please from the project requirements, you should stick to the design as much as possible. But as you can see you have some differences in the design. You can see the design below and compare it with your project design. :pray:

  | Your Design (With no margins in between the `about` and `works` sections and see project button width is more than the main `div`)|Figma Design (With margins and see project button width is not more than main `div`) |
  | :---:   | :---: | 
  | ![Screenshot from 2022-10-28 10-07-51](https://user-images.githubusercontent.com/92303891/198563199-12c8559d-b4a1-4d86-9f88-6e4ef889f4e2.png) | ![Screenshot from 2022-10-28 10-07-04](https://user-images.githubusercontent.com/92303891/198563252-f76fcd66-e5b5-4294-a531-70a12ef64834.png) |

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +        </div>
- [ ] Please you should not have the `alt` attribute empty for your images. You should add a descriptive `alt` attribute to your images. :pray:

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +        </div>
- [ ] Please make sure your see project button follows the button styling: Active, Hover, and Pressed to make it interactive. :pray:

 ![Screenshot from 2022-10-28 10-03-18](https://user-images.githubusercontent.com/92303891/198561604-0d202740-3ec3-48c3-bd51-4f73d6f92d63.png)

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +      </div>
- [ ] Please make sure your see project button follows the button styling: Active, Hover, and Pressed to make it interactive. :pray:

 ![Screenshot from 2022-10-28 10-03-18](https://user-images.githubusercontent.com/92303891/198561604-0d202740-3ec3-48c3-bd51-4f73d6f92d63.png)

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +      </div>
- [ ] Please make sure your see project button follows the button styling: Active, Hover, and Pressed to make it interactive. :pray:

 ![Screenshot from 2022-10-28 10-03-18](https://user-images.githubusercontent.com/92303891/198561604-0d202740-3ec3-48c3-bd51-4f73d6f92d63.png)

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +      </div>
- [ ] Please make sure your see project button follows the button styling: Active, Hover, and Pressed to make it interactive. :pray:

 ![Screenshot from 2022-10-28 10-03-18](https://user-images.githubusercontent.com/92303891/198561604-0d202740-3ec3-48c3-bd51-4f73d6f92d63.png)

2022-10-28 10:19 UTC, Owusu-Desmond commented on index.html
> +      </div>
- [ ] Please make sure your see project button follows the button styling: Active, Hover, and Pressed to make it interactive. :pray:

 ![Screenshot from 2022-10-28 10-03-18](https://user-images.githubusercontent.com/92303891/198561604-0d202740-3ec3-48c3-bd51-4f73d6f92d63.png)

2022-10-29 11:27 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @prg-04, 

Great work on making the changes requested by the previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet, but don't worry you're almost there!! 😉

![image](https://media3.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif?cid=ecf05e4734q298svfm6dye74pbw2yeu64ps29whho9qaoirw&rid=giphy.gif&ct=g)

 ## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please know that as the previous reviewer mentioned, you should stick to the design as much as possible. But as you can see you have some differences in the design:

  This is your design: 
  ![image](https://user-images.githubusercontent.com/20567503/198828698-1a767da3-bdc7-467c-a0f9-fd271d7ce95c.png)
  And this is the design provided in the Figma template:
  ![image](https://user-images.githubusercontent.com/20567503/198828714-bfae946d-cebd-45e8-b7db-96e9844ce0e0.png)

- [ ] As the previous reviewer mentioned, please know that the project buttons should follow the button styling provided: Active, Hover, and Pressed to make it interactive:

  ![image](https://user-images.githubusercontent.com/20567503/198828837-f4de2c41-2d35-4ee2-b8cb-4ea4eedbe194.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 11:27 UTC, mirouhml commented on index.html
> +          <img src="/images/plc-img.jpg" alt="" />
- [ ] As the previous reviewer mentioned, please know that you should leave the alt attributes empty for your images. You should add a descriptive alt attribute to your images. 🙏

2022-10-29 16:25 UTC, emmiiorji approved these changes
Hi @prg-04, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

 
![congratulations](https://user-images.githubusercontent.com/20554583/197318511-6afdd6f2-aa6f-4da6-8061-4899dec8c651.gif)


## Good Highlights✔

- Linter checks are passing
- Good commit message
- Adherence to GitHub flow

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 16:30 UTC, merged